### REGISTER USER

POST http://localhost:3000/api/auth/sign-up HTTP/1.1
content-type: application/json

{
    "name": "Yoel Almeda",
    "username": "yoel",
    "password": "s3cr3t",
    "email": "yoel@example.com"
}

### LOGIN

POST http://localhost:3000/api/auth/sign-in HTTP/1.1
content-type: application/json

{
    "email": "elyulidev@example.com",
    "password": "s3cr3t"
}

### LOGOUT

POST http://localhost:3000/api/auth/logout HTTP/1.1

### DASHBOARD USERS AUTHENTICATED

GET http://localhost:3000/api/dashboard HTTP/1.1

### GET ALL USERS

GET http://localhost:3000/api/admin/users HTTP/1.1

### DELETE USER

DELETE http://localhost:3000/api/admin/users/b91480a8-9856-422d-b8b0-ab1e50748d26 HTTP/1.1

### GET CURRENT USER

GET http://localhost:3000/api/users/me HTTP/1.1


